development:
  bucket_name: dhc-assets
  access_key_id: AKIAJHYYKGSZ5KWK4M4Q
  secret_access_key: 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

test:
  bucket_name: test_bucket
  access_key_id: 
  secret_access_key: 

production:
  bucket_name: production_bucket
  access_key_id: 
  secret_access_key: 
